### ISSUE TITLE
Game crashing after click TouchScreenButton with box2d

### ISSUE THREAD

**Issue by ismailgamedev** [appsinacup/godot-box2d#57]
Game crashing after click TouchScreenButton with box2d

**Comment by Ughuuu** [comment]
Can you provide a reproducible example? Also do note that body pickable https://github.com/appsinacup/godot-box2d/issues/6 is not yet impl. Not sure if it's needed for this or not.

**Comment by Ughuuu** [comment]
Same here, put a reproducible example. Also, I think now after the rewrite everything should work fine, including this. Reopen with reproducible example.
