### ISSUE TITLE
Bug: Parent scaling not respected on CollisionPolygons

### ISSUE THREAD

**Issue by Scuas** [appsinacup/godot-box2d#62]
I noticed that it appears area2Ds do not like to be scaled with Box2D! 

I've not tested how far this goes but I know the bug can be reproduced as follows:

Create a sprite 
Add child area2D and debug_print things which should react to collisions like _body_just_entered(body)
Set up a collisionpolygon2d child so the area2D works
Set the original sprite's scale to 200 and throw some rigidbodies at it.

You will notice that the rigidbody responds as if it were unscaled, the polygon's visuals and actual detection are now mis-matched due to the scaling.

**Comment by Ughuuu** [comment]
Thanks for the bug report.

Can you tell me the following:

Godot version(eg v4.2?)
This plugin version(eg v0.8?)
A project that reproduces this.
Does this happen in godot as you want it to, or does godot also have this problem?

Thanks

**Comment by arkology** [comment]
As I remember, Godot doesn't support scaling for physics, so this problem is on Godot side.

**Comment by Ughuuu** [comment]
Fixed in latest rewrite
