### ISSUE TITLE
Add Element on CollisionPolygon2D Polygon causes Godot to crash

### ISSUE THREAD

**Issue by tomsep** [appsinacup/godot-box2d#63]
Using "Add Element" on Polygon property of CollisionPolygon2D node almost always causes Godot to crash. 

**To Reproduce**

1. Create StaticBody2D node.
2. Create CollisionPolygon2D node as child node.
3. Select CollisionPolygon2D node to open the Inspector.
4. (Optional) Create 3 or more points with mouse.
5. Edit Polygon property by adding new points to it using "Add Element" button.
This will crash Godot if there are 3 or more points.

Occasionally Godot will also crash when moving points using mouse.

**Expected behavior**
Godot does not crash when editing the shape.

**Versions:**
 - OS: Win 10
 - Godot v4.2 beta 3
 - Box2d v0.8

**Comment by Ughuuu** [comment]
Fixed in the rewrite.
