### ISSUE TITLE
DampedSpringJoint2D as buggy as in godot physics

### ISSUE THREAD

**Issue by Griiimon** [appsinacup/godot-box2d#65]
Is the DampedSpringJoint2D implemented/tested in this version? 

For me it's as buggy as in godot physics, completely unusable. Any change in the settings and it glitches.

**Comment by Ughuuu** [comment]
Tested it in latest release from GitHub and works well for me. Can you show a video or a repro project with some values that don't work for you?

**Comment by Ughuuu** [comment]
Ok so unless you add an example with how it's buggy for your use case, in my tests it works well. Reopen with example project.

**Comment by Griiimon** [comment]
Sorry for the late reply. I made a bad beginner mistake and dragged the Collision Shape instead of the whole body, so the center of mass was way off and that lead to most of the glitches.

It indeed works way better than godots default spring, but I'm still getting unpredictable behavior

[Box2D Suspension.zip](https://github.com/appsinacup/godot-box2d/files/13393547/Box2D.Suspension.zip)

In this example neither the Rest Length nor the Length (Maximum length) is respected. I print the distance to the Joint in the console so you can compare it to the actual joint settings. You can use the mouse to pull on the Rigidbody.

It doesnt come to rest at the Rest Length and it's possible to drag it further than the maximum Length..

**Comment by Ughuuu** [comment]
Ok, seems to work but you set the anchor badly. The way you set it up you set the anchor way outside the second body. If you set it correctly, it works as expected.

**Comment by Ughuuu** [comment]
Let me know if you get it working also and if you have another issue reopen this issue

**Comment by Griiimon** [comment]
Of course, that makes a lot of sense. Now it does work as expected until I increase the weight on the Rigidbody.

It will still be able to exceed the maxium length:
[Box2D Suspension Update.zip](https://github.com/appsinacup/godot-box2d/files/13400613/Box2D.Suspension.Update.zip)

Another issue I'm having with this joint is that I originally just wanted a spring fixed on one axis. I realize that it's possible to increase the Damping ( even way beyond what the documentation states is the maximum of 1 ) but it still aligns very sluggishly to the axis. 

I kinda expected to get an effect that resembles a locked axis at maximum Damping. Especially since there is no alternative spring joint that has this behavior. I guess otherwise I would have to use a Groove Joint and implement a spring algorithm for the connected body myself.

Maybe it would be possible to make the Damping have more impact, or exponential impact in this addon? I don't know how Box2D handles this internally.

**Comment by Ughuuu** [comment]
Could you use both a groove joint and spring for this effect?
I could make the damping have more effect, but sould it be different from what godot does for spring? If so maybe it makes sense to increase the godot limits, thus changing api and also increasing this one.
All in all i could multiply damping by mass? But again would make sure in godot is same. Is damping influenced by mass in godot?

**Comment by Griiimon** [comment]
So, it turns out the my last project somehow was set on the default physics engine. Switching to Box2D made the length limit work! Sorry again, I really don't like to raise issues on github at all because 99% is just me making stupid mistakes in my projects.


> Could you use both a groove joint and spring for this effect?

I don't think so. The Dampened Spring Joint has to many features already. I'd rather have a fixed Spring Joint and if needed combine it with a Pin Joint to make it rotate like the Dampened Spring Joint does. If Godot had (working) basic Joints that could be combined to make something more complex instead of non-working complex Joints that are unusable that would be a game changer.
I think the only solution for now is to provide interfaces to other physics engines joints that aren't even present in godot.


> Is damping influenced by mass in godot?

I don't think that these kind of things are documented or even implemented correctly at the moment. The joints are so buggy that I only use the most basic one like Pin or Hinge and otherwise either code the behavior myself or use extensions like Jolt or this one.

**Comment by Ughuuu** [comment]
Np. Good thing it's working.
