### ISSUE TITLE
AnimatableBody2D gets rotated (inconsistently)

### ISSUE THREAD

**Issue by funjobie** [appsinacup/godot-box2d#70]
**Describe the bug**
I have a AnimatableBody2D that i rotate based in user input. (2 pinball flippers).
somehow, and only with bod2d enabled, one of them gets rotated by physics.

**To Reproduce**
1. open the provided project
2. press shift a few times to flip the paddles
3. see that the right paddle gets rotated, while the left paddle stays within its intended rotations

**Expected behavior**
I expect the physics engine to never change the rotation of an AnimatableBody2D 

**Project**
[flippers_rotated_2023_11_19_1.zip](https://github.com/appsinacup/godot-box2d/files/13402769/flippers_rotated_2023_11_19_1.zip)
<img width="579" alt="weird_rotation" src="https://github.com/appsinacup/godot-box2d/assets/8487260/9c7c6c03-4535-476a-8146-2bb21274b325">

is attached

**Versions (please complete the following information):**
 - OS: Windows
 - Godot v4.2.rc1.mono.official [ad72de508]
 - Box2d 0.9.1

**Comment by funjobie** [comment]
not sure if its in any way related but i also see two errors in the console:

src\box2d-wrapper\box2d_wrapper.cpp:1023 - Condition "half_height < radius + 0.00001f" is true. Returning: invalid_shape_handle()
  src\shapes\box2d_shape_2d.cpp:25 - Error creating the shape

**Comment by Ughuuu** [comment]
It is. It seems it doesn't create the shape correctly. I'll take a look.

**Comment by Ughuuu** [comment]
I'm courious, why should the physics engine never change the rotation of an animatable body?

**Comment by Ughuuu** [comment]
Ok, I think I see what's going on. How the kinematic body works currently, I set an angular velocity to the body until final state. I think in this case, the angular velocity is way too big, or it tries to go to wrong direction(angles have sign, so if it tries to go from 1.5 to -1.5 the longer way, the velocity might be bigger).
I could just teleport the body to the new rotation in this case.

**Comment by funjobie** [comment]
Well regarding my expectation. i am far from an expert, but this was my interpretation of the godot node documentation

"A 2D physics body that can't be moved by external forces. When moved manually, it affects other bodies in its path.
An animatable 2D physics body. It can't be moved by external forces or contacts, but can be moved manually by other means such as code, AnimationMixers (with AnimationMixer.callback_mode_process set to AnimationMixer.ANIMATION_CALLBACK_MODE_PROCESS_PHYSICS), and RemoteTransform2D.
When AnimatableBody2D is moved, its linear and angular velocity are estimated and used to affect other physics bodies in its path. This makes it useful for moving platforms, doors, and other moving objects."

which my reading was that the position/rotation is only changed explicitly by the user in order to affect other nodes.
As opposed to RigidBody2D, which is not meant to be controlled directly but rather only in response to physics.

**Comment by Ughuuu** [comment]
True. I just read your issue and it says there:

Expected behavior
I expect the physics engine to never change the rotation of an AnimatableBody2D

That's what threw me off a little. Yes, you should change rotation or position, and the physics engine will estimate the velocity based on that.

**Comment by Ughuuu** [comment]
I pushed a fix, it fixed the issue in my test. You can check it after it builds on master.

**Comment by funjobie** [comment]
thanks!

**Comment by Ughuuu** [comment]
Thanks for reporting it!
