### ISSUE TITLE
Collision shapes behave as if they are bigger than what it should be

### ISSUE THREAD

**Issue by DeeJayLSP** [appsinacup/godot-box2d#72]
**Describe the bug**
CharacterBody2D collisions (I haven't tested other body types) behave like they are somewhat bigger than what shows with Visible Collision Shapes on.

### Box2D/Rapier2D
![off](https://github.com/appsinacup/godot-box2d/assets/60024671/a63f771d-672b-4a42-ae12-f8ef3abc70ac)

**To Reproduce**
1. Make a 2D platformer like the one above.
2. Move the character to a wall and see the distance between the shapes.

**Expected behavior**
The same as the Rapier2D example above.

*If this is intended at least could be documented*

**Versions (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - Godot [v4.2 beta5]
 - Box2d [v0.9.2]

**Comment by Ughuuu** [comment]
Interesting. I think this is the polygon skin that box2d has. I have removed it in the past, but forgot in this new impl. I will document it in the readme, and I think I would wait for box2d v3 to appear(as that one doesnt use this polygon skin anymore).

You can view progress state here: https://github.com/erincatto/box2c/issues/44

**Comment by Ughuuu** [comment]
Added a documentation in the readme:
<img width="867" alt="image" src="https://github.com/appsinacup/godot-box2d/assets/2369380/b199ffbd-89be-441b-9087-bf79af16e1a0">
Hope box2c will fix it by removing polygon skin.
