### ISSUE TITLE
rotation inconsistencies

### ISSUE THREAD

**Issue by funjobie** [appsinacup/godot-box2d#74]
**Describe the bug**
while the fix in #71 helped quite a bit, i still believe there is some weirdness in how rotations of bodies are handled.
Depending on how my AnimatableBody2D is rotated, i can observe anything from extreme velocity increases to clipping.
The master with #73 in particular is more erratic.

![grafik](https://github.com/appsinacup/godot-box2d/assets/8487260/d0d58521-72b6-48af-9839-3e4148ab39b7)

**To Reproduce**
1. Open the scene and play
2. press r to spawn pinballs over the left and right flipper
3. interact with the marbles using shift or ctrl (shift is now a lower velocity flip, ctrl is higher velocity flip with initial delay)
4. observe that the right flipper causes extreme velocity increases, sometimes flips by itself, and sometimes the marble clips through it
5. stop play
6. very slightly change the rotation of FlipperR in game GameScene.tscn from 142.6 down to 140.
7. play again
8. observe that the physics are working perfectly fine

**Expected behavior**
Consistent physics no matter how bodies are rotated

**Project**
If applicable, add a reproducible project to help explain your problem.
[project_wild_rotations_2023_11_23_1.zip](https://github.com/appsinacup/godot-box2d/files/13453331/project_wild_rotations_2023_11_23_1.zip)

**Versions (please complete the following information):**
 - OS: Windows
 - Godot v4.2.rc1.mono.official [ad72de508]
 - Box2d master with #73 
 - Box2d master with #71 is "better" - however in that version the marble clips every single time through the right flipper on the ctrl flip (and also works perfectly fine when changing the rotation from  142.6 down to 140)

**Comment by Ughuuu** [comment]
Ok hopefully now it should really be fixed. https://github.com/appsinacup/godot-box2d/pull/75

Give it a try after it builds.
