### ISSUE TITLE
body_entered collisions events are sometimes missed

### ISSUE THREAD

**Issue by tomsep** [appsinacup/godot-box2d#76]
**Describe the bug**
body_entered event of RigidBody2D is not always called when collision happens. This is frequent when the colliding body moves fast and bounces off a surface.

When comparing Godot Physics with Box2D it seems that Godot Physics always reports the collision successfully. However, with Box2D it is missed often. Most likely the event is not propagated to Godot side if the contact only happens during physics sub-stepping.

**To Reproduce**
Use the attached project. Play the scene. A ball is shot towards a wall and bounces off it. A message is printed when body_entered event is called for the ball.

Run it first with using Godot Physics. The message is always printed. Then try with Box2D. The message is usually not printed.

If you reduce the initial speed of the ball enough then the Box2D will also begin to print the message, but can still sometimes miss.

**Expected behavior**
Expected that body entered and exit events are reliably called as it does with Godot Physics.

**Project**
Attached test project 
[CollisionMissedBug.zip](https://github.com/appsinacup/godot-box2d/files/13491781/CollisionMissedBug.zip)

**Versions (please complete the following information):**
 - OS: Windows 10
 - Godot v4.2 rc2
 - Box2d v0.9.2

**Comment by Ughuuu** [comment]
Ok, I was checking if there was a separation in PostSolve, but there are cases when there isn't, and they are colliding. Anyway, probably I shouldn't check if they are colliding or not, since the callback is called anyway when collision happens(probl has to do with sub stepping). After I removed that if the events are generated correctly.
