### ISSUE TITLE
Doesn't work collide function.

### ISSUE THREAD

**Issue by cplus98** [appsinacup/godot-box2d#80]
**Describe the bug**
The code is simple, but it doesn’t work.
It works well when set to GodotPhysics2D.

	var circle1 := CircleShape2D.new()
	var circle2 := CircleShape2D.new()
	var result = circle1.collide(Transform2D.IDENTITY, circle2, Transform2D.IDENTITY)
	print(result)

**To Reproduce**
The application terminates at the collision call.

**Expected behavior**
It should return true without any problems.

**Versions (please complete the following information):**
 - OS: OSX
 - Godot v4.2
 - Box2d v0.9.2

**Comment by Ughuuu** [comment]
I can reproduce it locally, I get a crash by calling that. Will investigate soon-ish.
