### ISSUE TITLE
Plugin startup has a warning.

### ISSUE THREAD

**Issue by Shadowdragon019** [appsinacup/godot-box2d#87]
**Describe the bug**
There isn't an "author" key in plugin.cfg, which causes Godot to not load the plugin

**To Reproduce**
1. Install Godot Box2D
3. Get an warning saying `editor/editor_plugin_settings.cpp:81 - Plugin config misses "plugin/author" key: res://addons/godot-box2d/plugin.cfg`

**Expected behavior**
For the plugin to be loaded without issue

**Project**
n/a

**Versions (please complete the following information):**
 - OS: Windows
 - Godot 4.2
 - Box2d 0.9.6

**Comment by Ughuuu** [comment]
Just fyi, the plugin just enabled the physics backend to box2d. Will fix, thx for reporting

**Comment by Ughuuu** [comment]
Also, for whoever is reading, the plugin starts up, that is just a warning that does not influence anything.
