### ISSUE TITLE
PinJoint2D always has "disable_collision" as "true"

### ISSUE THREAD

**Issue by BendySonic** [appsinacup/godot-box2d#92]
It's easy, when I connect two RigidBody2D using PinJoint2D, they can't collide each other. Same layer, same masks, "disable_collisions" was set to "false"

**Expected behavior**
Connected bodies collide each other.

**Versions (please complete the following information):**
 - OS: Windows
 - Godot v4.2
 - Last version of Box2D from AssetLib

**Comment by Ughuuu** [comment]
Sorry for delay, will look into this now and fix it.

**Comment by Ughuuu** [comment]
Ok, it seems the collide connected requires the destroy of joint that exists, hm.
